// This file is generated by assets/update.ts - DO NOT EDIT MANUALLY
// Run 'bun assets/update.ts' to regenerate this file
// Last generated: 2026-05-05T07:27:08.000Z

import type { FiletypeParserOptions } from "./types.js"

// `new URL(rel, import.meta.url)` is the portable asset-reference primitive: every bundler
// (Vite/rolldown, Bun, esbuild, webpack) emits the referenced file and rewrites the URL instead of
// parsing it as a JS module — so the .scm query files and grammar .wasm stay bundler-portable. In a
// native runtime it resolves to a file:// URL the parser worker reads; in a browser/worker bundle it
// resolves to an emitted asset URL the worker fetches.
const asset = (rel: string): string => new URL(rel, import.meta.url).href

// Cached parsers to avoid re-resolving on every call
let _cachedParsers: Promise<FiletypeParserOptions[]> | undefined

export function getParsers(): Promise<FiletypeParserOptions[]> {
  if (!_cachedParsers) {
    _cachedParsers = loadParsers()
  }
  return _cachedParsers
}

async function loadParsers(): Promise<FiletypeParserOptions[]> {
  return [
    {
      filetype: "javascript",
      aliases: ["javascriptreact"],
      queries: {
        highlights: [asset("./assets/javascript/highlights.scm")],
      },
      wasm: asset("./assets/javascript/tree-sitter-javascript.wasm"),
    },
    {
      filetype: "typescript",
      aliases: ["typescriptreact"],
      queries: {
        highlights: [asset("./assets/typescript/highlights.scm")],
      },
      wasm: asset("./assets/typescript/tree-sitter-typescript.wasm"),
    },
    {
      filetype: "markdown",
      queries: {
        highlights: [asset("./assets/markdown/highlights.scm")],
        injections: [asset("./assets/markdown/injections.scm")],
      },
      wasm: asset("./assets/markdown/tree-sitter-markdown.wasm"),
      injectionMapping: {
        nodeTypes: {
          inline: "markdown_inline",
          pipe_table_cell: "markdown_inline",
        },
        infoStringMap: {
          javascript: "javascript",
          js: "javascript",
          jsx: "javascriptreact",
          javascriptreact: "javascriptreact",
          typescript: "typescript",
          ts: "typescript",
          tsx: "typescriptreact",
          typescriptreact: "typescriptreact",
          markdown: "markdown",
          md: "markdown",
        },
      },
    },
    {
      filetype: "markdown_inline",
      queries: {
        highlights: [asset("./assets/markdown_inline/highlights.scm")],
      },
      wasm: asset("./assets/markdown_inline/tree-sitter-markdown_inline.wasm"),
    },
    {
      filetype: "zig",
      queries: {
        highlights: [asset("./assets/zig/highlights.scm")],
      },
      wasm: asset("./assets/zig/tree-sitter-zig.wasm"),
    },
  ]
}
